version: 2
updates:
  - package-ecosystem: poetry
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      dev-dependencies:
        dependency-type: development
      optional-ml:
        patterns:
          - "torch"
          - "transformers"
          - "pillow"
          - "python-doctr"
          - "nltk"
          - "networkx"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
