[tool.poetry]
name = "silverspeak"
version = "2.3.0"
description = "A Python library to perform homoglyph-based attacks on text. It supports both identical and non-identical homoglyphs across multiple languages."
readme = "README.md"
license = "GPL-3.0"
authors = ["Aldan Creo <os@acmc.fyi>"]
keywords = [
    "homoglyph", "attack", "text", "security", "obfuscation", "phishing", 
    "spoofing", "unicode", "cybersecurity", "text-manipulation", 
    "text-security", "character-substitution", "text-obfuscation", 
    "identity-theft", "data-protection", "adversarial-attacks", 
    "unicode-homoglyphs", "text-attacks", "cyber-attacks", "information-security"
]

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
pandas = "^2.2.2"
unicodedataplus = "^16.0.0.post1"
transformers = "^4.51.3"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"
pytest = "^8.3.5"
sphinx = "^7.0.0"
sphinx_rtd_theme = "^1.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.setuptools]
packages = ["silverspeak", "silverspeak.homoglyphs"]

[tool.setuptools.package-data]
"silverspeak.homoglyphs" = ["identical_map.json", "unicode_confusables_map.json", "ocr_chars_map.json", "ocr_chars_refined_map.json"]
