name: Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: true
      
      - name: Install dependencies
        run: |
          poetry install --with dev
      
      - name: Lint with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          poetry run flake8 silverspeak/ --count --select=E9,F63,F7,F82 --show-source --statistics
          # Exit-zero treats all errors as warnings
          poetry run flake8 silverspeak/ --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics
      
      - name: Check formatting with black
        run: |
          # Add --quiet to suppress info output and only show errors
          # Use --force-exclude to ensure certain patterns are always excluded
          poetry run black --check --diff --quiet silverspeak/
          # Return exit code 0 to avoid failing the build on formatting issues
          exit 0
      
      - name: Check import sorting with isort
        run: |
          poetry run isort --check --diff silverspeak/
      
      - name: Type check with mypy
        run: |
          poetry run mypy --ignore-missing-imports silverspeak/